run:
  mode: simulator
strategy:
  symbols: ["BTC-PERP","ETH-PERP"]
  width_vol_mult: 1.6
  inv_skew_strength: 0.35
  imbalance_skew_strength: 0.25
  funding_bias_strength: 0.1
risk:
  daily_loss_limit_usd: 200
  max_portfolio_var_usd: 120
compliance:
  max_amends_per_sec: 2
ti_proxy:
  target_maker_ratio: 0.7
